### PR TITLE
No-Code Device Submission

### PR DESCRIPTION
**Pull request by bmos**
Some users may not be comfortable editing a JSON file to contribute information about the batteries in their devices.

Thanks to [GitHub Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms), combined with GitHub Actions, an easy no-code submission process is possible that will allow anyone with a GitHub account to contribute to the library by filling out [a form via the Issues tab](https://github.com/bmos/HA-Battery-Notes/blob/automatic-device-definitions/.github/ISSUE_TEMPLATE/new-device.yml).

### CODE REVIEW

**Comment by bmos** [comment]
I haven't been able to get the list sorting working, so dive in if that's important to you.
Fortunately that section is in python.

**Comment by andrew-codechimp** [comment]
Thanks, I'll spend some time to understand this before releasing but really appreciate what you've done here, it will hopefully mean less malformed json to edit.

I'm rapidly coming to the conclusion that sorting isn't necessary and I'm using Find to track down devices so I may drop that requirement and avoid the pain.

**Comment by andrew-codechimp** [comment]
Thanks so much for this, I had to tweak it a little on the int for battery quantity but just put it live with a beta link on the readme.

**Comment by bmos** [comment]
Looks like it ran into an issue and had to be disabled?
It also appears to have been sorting by name automatically.
I'm guessing the issue might have been that when multiple users submitted these relatively far-reaching PRs (re-ordering items and removing trailing whitespaces) they invalidated other PRs that were open?

If so the two potential solutions I see are:
1. Disable the automatic sorting (which still leaves the end of line issues unless we add the new definition to the file via line editing rather than via a json parser/writer)
2. Apply the same automatic sorting and end-of-line fixes to any Pull Request that touches that file (which should mean they can merge cleanly).

**Comment by bmos** [comment]
Anyway, happy to help however I can to get that working.

**Comment by andrew-codechimp** [comment]
Yeah, it was doing very odd PR's so I disabled it for now, as you say I think it was where there was manual PR's confusing it.

I'm going to setup a shadow repo to test this more fully as it's something I'd like to add to save some manual effort each day but at the moment I'm not getting a lot of time.

**Pull request merged**
