### PR TITLE
auto-sort and format library.json after a push

### PR DESCRIPTION
**Pull request by bmos**
Parses json, sorts by manufacturer+model, and writes back to file (eliminating trailing whitespace, fixing alphabetizing, and other jank)

### CODE REVIEW

**Comment by bmos** [comment]
feel free to mine this for ideas instead of merging.

the final commit on this is an example of what the resulting commit will look like

**Comment by bmos** [comment]
I have updated it to just run on "push" as a merged PR will always create a push event to the branch it's being merged onto.

**Comment by bmos** [comment]
it might also make sense to implement an automatic cleanup of any duplicates that have been manually added

**Comment by andrew-codechimp** [comment]
Thanks for your continued interest in this, I will have a look at this soon, the sorting will be useful as I'm hitting a lot of PR's that don't come sorted.

**Comment by andrew-codechimp** [comment]
I'm not seeing too many people having an extra last comma
@bmos has done some great work on a device issue template which would make it far easier but not quite ready yet and I'm still catching up on features to look at this, GH actions are really frustrating to test.

**Comment by bmos** [comment]
You can say that again!
If the comma means the json doesn't parse, the json validator will complain. If it does parse, then this should remove the comma.

**Comment by bmos** [comment]
One thing I have noticed is that some JSON characters are being automatically escaped that are not escaped by some folks who contribute manually.

**Comment by andrew-codechimp** [comment]
I do a trial json load before updating the library so they will at least be caught if they were going to cause a problem.

**Comment by andrew-codechimp** [comment]
Now that I've done with the large features I may get some time to look at this more.
Trying out issues/pr's/scripts on a fork is a little dangerous.
I've created a temp repo and invited you as a contributor, that way we can try as many edits as we want without danger.
The repo is up to date with your patch and the main branch here.
https://github.com/andrew-codechimp/bn-device-test

**Comment by bmos** [comment]
> I've created a temp repo

Can you enable issues on the temp repo?

**Comment by bmos** [comment]
In merging the library here, I overwrote what I had in my branch with what you have in main in case I had messed anything up during testing.

**Comment by bmos** [comment]
It should be all ready for a merge :)

**Comment by andrew-codechimp** [comment]
I've just added the scripts and merged.
Thanks for all your work on this, it will hopefully make the library grow and save me a lot of time.

I'm leaving the other repo hanging about so I can test stuff in future, if you want to test any changes feel free to over there.

**Pull request merged**
