### PR TITLE
Attribs

### PR DESCRIPTION
**Pull request by andrew-codechimp**

### CODE REVIEW

**Comment by nechry** [comment]
just curious, would it be possible to add theres attributes directly to the battery entity? basically like I do with the customize. if yes by adding the last replacement date I could directly use my battery report

**Comment by andrew-codechimp** [comment]
I'll have a look at how customize adds attributes and see if it's possible from another integration.  It would make life easier if I can get them onto the battery entity as well.

**Comment by andrew-codechimp** [comment]
Customize is adding attributes when the sensor updates, looking at how it does it it clears all existing attributes and re-creates them so if I forced an attribute on the battery sensor it would be removed when the sensor refreshes so doesn't look like I'll be able to do this.  Shame as that would open up some interesting possibilities.
I'll continue with the attributes on the battery_type sensor which will I'll put in a release within the next week.

**Comment by nechry** [comment]
ok thank you for this try, it's a shame that HA doesn't try to merge the attributes instead of replacing them. but I will already be happy to get attributes about battery type as in the original request anyway. thanks again

**Pull request merged**
