### PR TITLE
Added a few devices

### PR DESCRIPTION
**Pull request by cs42**
eQ-3: HmIP-WTH-2
a few Zigbee devices with deCONZ: Develco (AQSZB-110), eWeLink (TH01), IKEA (Tradfri ON/OFF, SYMFONISK, RODRET), LUMI/Aqara (Opple switch, temperature, water leak, illuminance, cube, magnet)

### CODE REVIEW

**Comment by andrew-codechimp** [comment]
Thanks

**Comment by emilianox** [comment]
what device is  eWeLink (TH01) ?
I have a bunch of https://zigbee.blakadder.com/Sonoff_SNZB-02.html and they use 2450 batteries...

**Comment by andrew-codechimp** [comment]
Agreed, also the Develco uses AA not AAA, both fixed in latest commit

https://github.com/andrew-codechimp/HA-Battery-Notes/commit/10e2c18b321a513f56095737d8e2d8f8f6e2a998

**Comment by cs42** [comment]
> what device is eWeLink (TH01) ? I have a bunch of https://zigbee.blakadder.com/Sonoff_SNZB-02.html and they use 2450 batteries...

Sorry, got confused, they use CR2450. I think it's a SNZB-02, but deCONZ reports it as eWeLink TH01.

**Pull request merged**
